export default {
  DEBUG: false,

  HEALTH_MAX: 100,

  STAMINA_MAX: 100,
  STAMINA_USE_FLYING: 2,
  STAMINA_RECOVERY_IDLE: 0.5,
  STAMINA_RECOVERY_WALKING: 0.3,

  SPEED_WALKING: 50,
  SPEED_FLYING: 150,
  SPEED_ASCEND: 200,
  SPEED_GRAVITY: 10,

  ITEM_MAX_CARRIED: 3,
  ITEM_MAX_WEIGHT_FACTOR: 0.5,
  ITEM_WEIGHT_FACTOR_COEF: 10
}
