export default {
  DEBUG: true,

  SCENE_WIDTH: 1280,
  SCENE_HEIGHT: 720,

  HEALTH_MAX: 100,

  STAMINA_MAX: 100,
  STAMINA_USE_FLYING: 2,
  STAMINA_RECOVERY_IDLE: 0.5,
  STAMINA_RECOVERY_WALKING: 0.3,

  SPEED_WALKING: 50,
  SPEED_FLYING: 150,
  SPEED_ASCEND: 200,
  SPEED_GRAVITY: 10,

  ITEM_MAX_CARRIED: 3,
  ITEM_MAX_WEIGHT_FACTOR: 0.5,
  ITEM_WEIGHT_FACTOR_COEF: 10,

  CITIZEN_MAX_COUNT: 5,
  CITIZEN_FREQUENCY: 100,
  CITIZEN_DAMAGE: 10,

  SHADOWBLIGHT_DAMAGE: 20,

  CAT_DAMAGE: 30,

  NEST_WIDTH: 128,
  NEST_HEIGHT: 128,

  OBJECTS_SHADOW_ALPHA: 0.2
}
