export default {
  DEBUG: false,

  HEALTH_MAX: 100,

  STAMINA_MAX: 100,
  STAMINA_USE_FLYING: 3,
  STAMINA_RECOVERY_IDLE: 0.5,
  STAMINA_RECOVERY_WALKING: 0.3,

  SPEED_WALKING: 100,
  SPEED_ASCEND: 200,
  SPEED_GRAVITY: 10
}
